env:
  browser: false
  commonjs: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: "module"
plugins:
  - "@typescript-eslint"
rules:
  {
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/explicit-module-boundary-types": "off",
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/ban-types":
      [
        "error",
        {
          "types":
            {
              "String": true,
              "Boolean": true,
              "Number": true,
              "Symbol": true,
              "{}": false,
              "Object": false,
              "object": false,
              "Function": true,
            },
          "extendDefaults": true,
        },
      ],
    "@typescript-eslint/quotes":
      [
        "error",
        "double",
        { "avoidEscape": true, "allowTemplateLiterals": true },
      ],
  }
ignorePatterns: ["*.js", "dist", "test", "envs"]


